flowchart TD
  risk_REQ_005[污染、样本损失] --> REQ_005[R7]
  risk_REQ_006[污染、样本损失] --> REQ_006[R8]
  risk_REQ_013[配平失败、温升导致样本降解] --> REQ_013[R7]
  risk_REQ_014[配平失败、温升导致样本降解] --> REQ_014[R8]
  risk_REQ_022[污染、沉淀丢失、人工判断偏差] --> REQ_022[R7]
  risk_REQ_023[污染、沉淀丢失、人工判断偏差] --> REQ_023[R8]
  risk_REQ_031[污染、样本损失、人工判断偏差] --> REQ_031[R7]
  risk_REQ_032[污染、样本损失、人工判断偏差] --> REQ_032[R8]
